version: 0.2

phases:
  install:
    commands:
      # install node 15
      - curl -sL https://deb.nodesource.com/setup_15.x | bash -
      - apt-get install -y nodejs
      # install mongo
      - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
      - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
      - apt update
      - apt upgrade -y
      - apt install -y mongodb-org
  pre_build:
    commands:
      # start mongo
      - sudo systemctl start mongod
  build:
    commands:
      #start
      npm start
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: /
